name: 'Lint'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Nodejs Environment
        uses: actions/setup-node@v2
        with:
          node-version: 17
          
      - name: Setup PNPM Environment
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install Package(s)
        run: pnpm install

      - name: Check Code Problem(s)
        run: pnpm run lint
